#!/bin/bash

SUITES="spec_fp spec_int parsec"

PLOTTING_COMMAND="set terminal pdf"
PLOTTING_COMMAND="${PLOTTING_COMMAND}\nset output \'reporter_timeseries.pdf\'"
PLOTTING_COMMAND="${PLOTTING_COMMAND}\nset ylabel \'IPC\'"
PLOTTING_COMMAND="${PLOTTING_COMMAND}\nset xlabel \'Time (m)\'"
#PLOTTING_COMMAND="${PLOTTING_COMMAND}\n set xtics 20"

REP=1
for SUITE in ${SUITES}; do
    for BMARK in `cat "manifests/${SUITE}_benchmarks"`; do
        INPUT="data/${SUITE}.${BMARK}.${REP}.reporter.ipc"
        PLOTTING_COMMAND="${PLOTTING_COMMAND}\nset title \'${BMARK}\'"
        PLOTTING_COMMAND="${PLOTTING_COMMAND}\nstats \'${INPUT}\' using 2 name \'${BMARK}\'" 
        PLOTTING_COMMAND="${PLOTTING_COMMAND}\nplot \'${INPUT}\' using (\$1/60):2 notitle with lines, ${BMARK}_mean title \'mean\' lw 3, ${BMARK}_median title \'median\' lw 3, ${BMARK}_min title \'minimum\' lw 3, ${BMARK}_max title \'maximum\' lw 3"
    done
done
printf "${PLOTTING_COMMAND}" | gnuplot
